name: online_food_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  get: 4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  flutter_gen_runner: null
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
